name: tada_beta
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2
  path_provider: ^2.0.11
  json_annotation: ^4.5.0
  audioplayers: ^6.0.0
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  shimmer: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/
    - lib/ui/assets/json/tasks.json
    - lib/ui/assets/json/user.json
    - lib/ui/assets/json/prizepools.json
    - lib/ui/assets/json/pp_user.json
    - lib/ui/assets/json/task_details.json
    - assets/audio/ohnon.m4a

