// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1PIh90WaFPQTDw0m-IqeOIyUA5Vbo444',
    appId: '1:853584609148:web:4cf984283fcab0a743aef9',
    messagingSenderId: '853584609148',
    projectId: 'tadacrash',
    authDomain: 'tadacrash.firebaseapp.com',
    storageBucket: 'tadacrash.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8DLKLgMslCV15BCfKrmDRt1NhPizMiJw',
    appId: '1:853584609148:android:0511c31c11dfd3d543aef9',
    messagingSenderId: '853584609148',
    projectId: 'tadacrash',
    storageBucket: 'tadacrash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqESthuqZggWHkxqy9xdDsM139h1TeHzk',
    appId: '1:853584609148:ios:c6fff5e45143123443aef9',
    messagingSenderId: '853584609148',
    projectId: 'tadacrash',
    storageBucket: 'tadacrash.appspot.com',
    iosBundleId: 'com.example.tadaBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqESthuqZggWHkxqy9xdDsM139h1TeHzk',
    appId: '1:853584609148:ios:c6fff5e45143123443aef9',
    messagingSenderId: '853584609148',
    projectId: 'tadacrash',
    storageBucket: 'tadacrash.appspot.com',
    iosBundleId: 'com.example.tadaBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1PIh90WaFPQTDw0m-IqeOIyUA5Vbo444',
    appId: '1:853584609148:web:17ca45b5faf1ee4443aef9',
    messagingSenderId: '853584609148',
    projectId: 'tadacrash',
    authDomain: 'tadacrash.firebaseapp.com',
    storageBucket: 'tadacrash.appspot.com',
  );
}
